fingerprints:
  enabled: true
  lifetime: 1800
  blocks:
    - chest
    - brewing_stand
    - furnace
    - blast_furnace
    - trapped_chest
    - barrel
    - oak_door
    - dark_oak_door
    - acacia_door
    - birch_door
    - spruce_door
    - crimson_door
    - jungle_door
    - mangrove_door
    - warped_door
    - iron_door
    - stone_button
    - polished_blackstone_button
    - stone_button
    - oak_button
    - dark_oak_button
    - acacia_button
    - birch_button
    - spruce_button
    - crimson_button
    - jungle_button
    - mangrove_button
    - warped_button
    - hopper
    - dropper
    - dispenser
    - trapped_chest
tool-attributes:
  enabled: true
  attribute-certainty: 0.3
  attributes:
    - Heavy
    - Medium
    - Light
  durability-certainty: 0.3
  durability:
    - Sharp
    - Dull
    - Chipped
    - Jagged
    - Broken
  tools:
    - wooden_pickaxe
    - wooden_shovel
    - wooden_sword
    - wooden_axe
    - wooden_hoe
    - stone_pickaxe
    - stone_shovel
    - stone_sword
    - stone_axe
    - stone_hoe
    - golden_pickaxe
    - golden_shovel
    - golden_sword
    - golden_axe
    - golden_hoe
    - iron_pickaxe
    - iron_shovel
    - iron_sword
    - iron_axe
    - iron_hoe
    - diamond_pickaxe
    - diamond_shovel
    - diamond_sword
    - diamond_axe
    - diamond_hoe
    - netherite_pickaxe
    - netherite_shovel
    - netherite_sword
    - netherite_axe
    - netherite_hoe